// PHASE 10E — STARTER 2026.1 canonical 콘텐츠 → 결정적 SQL (새 npm 의존성 없음)
// ---------------------------------------------------------------------
// 실행:  node content/starter/2026.1/build-sql.mjs            (파일 생성)
//        node content/starter/2026.1/build-sql.mjs --check    (생성 결과가 저장소 파일과 같은지만 확인 · exit 1 = 다름)
//
// 출력 (migration 이 아니다 — `supabase/migrations` 밖 · db push 로 적용되지 않는다):
//   supabase/content/starter_2026_1_load.sql     draft 프로그램 · 차시 8 · section 136 적재 (반복 실행 안전)
//   supabase/content/starter_2026_1_publish.sql  사람 승인 후에만: 필수 section 확인 → 차시 · 프로그램 게시
//
// 결정성: id = md5("soye-content:<key>") 를 UUID 형식으로 · 같은 입력 = 같은 SQL (시각 · 난수 없음).
// 안전: 삭제 없음 · 기존 합성 차시(STAGING-P8 등) · 계약 · 수업 · 관찰 · 리포트를 건드리지 않는다.
//       게시된 차시의 본문이 다르면 적재가 중단된다 (DEC-096: 게시본 조용한 수정 금지 → 새 버전).

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..", "..");
const OUT_DIR = join(ROOT, "supabase", "content");
const LOAD = join(OUT_DIR, "starter_2026_1_load.sql");
const PUBLISH = join(OUT_DIR, "starter_2026_1_publish.sql");

export const SECTION_CODES = ["s1", "s2", "s3", "s4a", "s4b", "s4c", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12", "s13", "s14", "s15"];
export const REQUIRED = ["s1", "s2", "s3", "s4a", "s4c", "s5", "s6", "s11", "s12", "s13", "s15"];

export function contentId(key) {
  const h = createHash("md5").update(`soye-content:${key}`).digest("hex");
  // RFC 4122 형태 (version 3 = MD5 name-based · variant 10xx)
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-3${h.slice(13, 16)}-${((parseInt(h[16], 16) & 0x3) | 0x8).toString(16)}${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

/** week-0N.txt → [{ code, label, body }] (순서 보존) */
export function parseWeekFile(text) {
  const sections = [];
  let current = null;
  for (const line of text.replace(/\r\n/g, "\n").split("\n")) {
    const m = line.match(/^=== (s\d+[abc]?) \| (.+)$/);
    if (m) {
      current = { code: m[1], label: m[2].trim(), lines: [] };
      sections.push(current);
    } else if (current) {
      current.lines.push(line);
    } else if (line.trim() !== "") {
      throw new Error(`section 표시 전의 내용: ${line.slice(0, 40)}`);
    }
  }
  return sections.map((s) => ({ code: s.code, label: s.label, body: s.lines.join("\n").trim() }));
}

export function loadPackage() {
  const manifest = JSON.parse(readFileSync(join(HERE, "manifest.json"), "utf8"));
  const weeks = manifest.weeks.map((w) => {
    const sections = parseWeekFile(readFileSync(join(HERE, w.file), "utf8"));
    return { ...w, sections };
  });
  return { manifest, weeks };
}

function dq(value, tag) {
  const text = String(value);
  if (text.includes(`$${tag}$`)) throw new Error(`본문에 dollar-quote 표시가 있다 (${tag})`);
  return `$${tag}$${text}$${tag}$`;
}

function sourceRef(week, section) {
  const src = week.source;
  const origin = week.section_source_map[section.code];
  const ref = `${src.filename} ${origin} (sha256:${src.sha256.slice(0, 16)}) → ${section.code} · STARTER 2026.1 PHASE 10E`;
  if (ref.length > 300) throw new Error(`source_ref 300자 초과 (W${week.week} ${section.code})`);
  return ref;
}

export function buildSql() {
  const { manifest, weeks } = loadPackage();
  const p = manifest.program;
  const programId = contentId(`program:${p.code}`);

  for (const w of weeks) {
    const codes = w.sections.map((s) => s.code);
    if (codes.join(",") !== SECTION_CODES.join(",")) throw new Error(`W${w.week} section 구성이 다르다: ${codes.join(",")}`);
    for (const s of w.sections) {
      if (!s.body) throw new Error(`W${w.week} ${s.code} 본문 없음`);
      if (s.body.length > 10000) throw new Error(`W${w.week} ${s.code} 10000자 초과`);
    }
    if (w.title.length > 150) throw new Error(`W${w.week} 제목 150자 초과`);
    if (w.objective.length > 1000) throw new Error(`W${w.week} objective 1000자 초과`);
  }

  const header = (purpose) => [
    "-- =====================================================================",
    `-- GENERATED by content/starter/2026.1/build-sql.mjs — 직접 수정하지 않는다 (canonical 파일을 고친 뒤 다시 생성)`,
    `-- ${purpose}`,
    "-- 원본: SOYE_KIDS_1~8주차_교사용_수업가이드.pdf (content/starter/2026.1/manifest.json · SHA-256 기록)",
    "-- HUMAN CONTENT APPROVAL REQUIRED — docs/11-production-readiness/phase-10e-starter-content-approval.md",
    "-- migration 이 아니다 · 트랜잭션 제어 없음 (호출자가 begin/commit) · 삭제 없음 · 사용자 · 계약 · 수업 · 기록 데이터 무관",
    "-- =====================================================================",
    "",
  ];

  const load = [...header("LOAD: draft 프로그램 1 · draft 차시 8 · 차시당 section 17 (필수 11 포함). 반복 실행 안전 (같은 내용이면 변화 없음)")];
  load.push("do $load$");
  load.push("declare");
  load.push("  v_status text;");
  load.push("  v_code text;");
  load.push("begin");
  load.push(`  select status, code into v_status, v_code from public.curriculum_programs where id = '${programId}';`);
  load.push("  if not found then");
  load.push(`    insert into public.curriculum_programs (id, code, title, summary, age_group, duration_weeks, status)`);
  load.push(`    values ('${programId}', ${dq(p.code, "t")}, ${dq(p.title, "t")}, ${dq(p.summary, "t")}, null, ${p.duration_weeks}, 'draft');`);
  load.push(`  elsif v_code is distinct from ${dq(p.code, "t")} then`);
  load.push(`    raise exception 'STARTER 2026.1 program id 충돌 (code=%)', v_code;`);
  load.push("  end if;");
  load.push("end;");
  load.push("$load$;");
  load.push("");

  for (const w of weeks) {
    const lessonId = contentId(`lesson:${p.code}:w${w.week}:s1`);
    load.push(`-- W${w.week} ${w.storybook} · 성장키워드 ${w.growth_keyword} · 원본 ${w.source.filename} sha256 ${w.source.sha256}`);
    load.push("do $load$");
    load.push("declare");
    load.push("  v_status text;");
    load.push("  v_body text;");
    load.push("  v_expected text;");
    load.push("begin");
    load.push(`  select status into v_status from public.curriculum_lessons where id = '${lessonId}';`);
    load.push("  if not found then");
    load.push(`    insert into public.curriculum_lessons (id, program_id, week_no, session_no, title, objective, duration_minutes, status)`);
    load.push(`    values ('${lessonId}', '${programId}', ${w.week}, 1, ${dq(w.title, "t")}, ${dq(w.objective, "t")}, null, 'draft');`);
    load.push("    v_status := 'draft';");
    load.push("  end if;");
    for (const s of w.sections) {
      const body = dq(s.body, "b");
      const ref = dq(sourceRef(w, s), "t");
      load.push(`  v_expected := ${body};`);
      load.push(`  select body into v_body from public.lesson_sections where lesson_id = '${lessonId}' and section_code = '${s.code}';`);
      load.push("  if not found then");
      load.push("    if v_status <> 'draft' then");
      load.push(`      raise exception 'W${w.week} 게시된 차시에 ${s.code} 가 없다 — 새 버전으로 적재해야 한다';`);
      load.push("    end if;");
      load.push(`    insert into public.lesson_sections (lesson_id, section_code, body, source_ref) values ('${lessonId}', '${s.code}', v_expected, ${ref});`);
      load.push("  elsif v_body is distinct from v_expected then");
      load.push("    if v_status <> 'draft' then");
      load.push(`      raise exception 'W${w.week} ${s.code} 게시본과 canonical 본문이 다르다 — 게시본은 조용히 고치지 않는다 (DEC-096)';`);
      load.push("    end if;");
      load.push(`    update public.lesson_sections set body = v_expected, source_ref = ${ref} where lesson_id = '${lessonId}' and section_code = '${s.code}';`);
      load.push("  end if;");
    }
    load.push("end;");
    load.push("$load$;");
    load.push("");
  }

  const lessonIds = weeks.map((w) => contentId(`lesson:${p.code}:w${w.week}:s1`));
  const publish = [...header("PUBLISH: 사람 콘텐츠 승인(W1~W8 체크박스) 후에만 실행한다. 필수 section 11개 확인 → 차시 8 · 프로그램 게시")];
  publish.push("do $publish$");
  publish.push("declare");
  publish.push("  v_missing text;");
  publish.push("begin");
  publish.push("  select string_agg(format('W%s:%s', l.week_no, r.code), ', ' order by l.week_no, r.code) into v_missing");
  publish.push("  from public.curriculum_lessons l");
  publish.push("  cross join unnest(private.required_lesson_sections()) as r(code)");
  publish.push(`  where l.id in (${lessonIds.map((id) => `'${id}'`).join(", ")})`);
  publish.push("    and not exists (select 1 from public.lesson_sections s where s.lesson_id = l.id and s.section_code = r.code);");
  publish.push("  if v_missing is not null then");
  publish.push("    raise exception 'STARTER 2026.1 필수 section 누락: %', v_missing;");
  publish.push("  end if;");
  publish.push(`  if (select count(*) from public.curriculum_lessons where id in (${lessonIds.map((id) => `'${id}'`).join(", ")})) <> 8 then`);
  publish.push("    raise exception 'STARTER 2026.1 차시 8개가 적재되지 않았다 (load 먼저 실행)';");
  publish.push("  end if;");
  publish.push(`  update public.curriculum_lessons set status = 'published' where id in (${lessonIds.map((id) => `'${id}'`).join(", ")}) and status = 'draft';`);
  publish.push(`  update public.curriculum_programs set status = 'published' where id = '${programId}' and status = 'draft';`);
  publish.push("end;");
  publish.push("$publish$;");
  publish.push("");

  return { load: load.join("\n"), publish: publish.join("\n"), programId, lessonIds };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { load, publish } = buildSql();
  if (process.argv.includes("--check")) {
    const lf = (p) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");
    const same = lf(LOAD) === load && lf(PUBLISH) === publish;
    console.log(same ? "generated SQL is up to date" : "generated SQL differs — run build-sql.mjs");
    process.exit(same ? 0 : 1);
  }
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(LOAD, load);
  writeFileSync(PUBLISH, publish);
  console.log(`wrote ${LOAD.replace(ROOT, ".")} (${load.length} chars) · ${PUBLISH.replace(ROOT, ".")} (${publish.length} chars)`);
}
