-- =====================================================================
-- GENERATED by content/starter/2026.1/build-sql.mjs — 직접 수정하지 않는다 (canonical 파일을 고친 뒤 다시 생성)
-- PUBLISH: 사람 콘텐츠 승인(W1~W8 체크박스) 후에만 실행한다. 필수 section 11개 확인 → 차시 8 · 프로그램 게시
-- 원본: SOYE_KIDS_1~8주차_교사용_수업가이드.pdf (content/starter/2026.1/manifest.json · SHA-256 기록)
-- HUMAN CONTENT APPROVAL REQUIRED — docs/11-production-readiness/phase-10e-starter-content-approval.md
-- migration 이 아니다 · 트랜잭션 제어 없음 (호출자가 begin/commit) · 삭제 없음 · 사용자 · 계약 · 수업 · 기록 데이터 무관
-- =====================================================================

do $publish$
declare
  v_missing text;
begin
  select string_agg(format('W%s:%s', l.week_no, r.code), ', ' order by l.week_no, r.code) into v_missing
  from public.curriculum_lessons l
  cross join unnest(private.required_lesson_sections()) as r(code)
  where l.id in ('0e412aa2-d8f4-3247-a8d8-7c79a8768646', '5bad87d5-ea08-3223-afdc-fbbc65476779', 'e479b103-ed89-3db8-9b32-fe41b8e73e24', 'f66dcae9-5404-37be-9831-af52b7ff8e14', '54b89857-dcb8-326a-b913-b622c47df14d', '3be90928-5f39-3456-b6b8-9f3a4eb396af', '6f902050-036f-324f-b255-2eceacea4f73', '8b00cc10-eb37-3143-960e-edf8208db5bd')
    and not exists (select 1 from public.lesson_sections s where s.lesson_id = l.id and s.section_code = r.code);
  if v_missing is not null then
    raise exception 'STARTER 2026.1 필수 section 누락: %', v_missing;
  end if;
  if (select count(*) from public.curriculum_lessons where id in ('0e412aa2-d8f4-3247-a8d8-7c79a8768646', '5bad87d5-ea08-3223-afdc-fbbc65476779', 'e479b103-ed89-3db8-9b32-fe41b8e73e24', 'f66dcae9-5404-37be-9831-af52b7ff8e14', '54b89857-dcb8-326a-b913-b622c47df14d', '3be90928-5f39-3456-b6b8-9f3a4eb396af', '6f902050-036f-324f-b255-2eceacea4f73', '8b00cc10-eb37-3143-960e-edf8208db5bd')) <> 8 then
    raise exception 'STARTER 2026.1 차시 8개가 적재되지 않았다 (load 먼저 실행)';
  end if;
  update public.curriculum_lessons set status = 'published' where id in ('0e412aa2-d8f4-3247-a8d8-7c79a8768646', '5bad87d5-ea08-3223-afdc-fbbc65476779', 'e479b103-ed89-3db8-9b32-fe41b8e73e24', 'f66dcae9-5404-37be-9831-af52b7ff8e14', '54b89857-dcb8-326a-b913-b622c47df14d', '3be90928-5f39-3456-b6b8-9f3a4eb396af', '6f902050-036f-324f-b255-2eceacea4f73', '8b00cc10-eb37-3143-960e-edf8208db5bd') and status = 'draft';
  update public.curriculum_programs set status = 'published' where id = '4f54cc7e-620f-374e-8937-e808e2afc1a9' and status = 'draft';
end;
$publish$;
